version: "3.9"
services: 
    d1:
        image: nginx
        ports: 
            - "3002:80"
    appweb:
        build: ./app-web
        # entrypoint: "bash"
        ports: 
            - "9090:80"
    postgresdb:
        image: postgres
        ports: 
            - "2727:5432"
        environment: 
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "password"
        volumes: 
            - "data:/var/lib/postgresql/data"
    appweb2:
        image: httpd
        ports: 
            - "9999:80"
        volumes: 
            - "./app-web/src:/usr/local/apache2/htdocs/"

volumes: 
    data:

